# Dev image

# Builder image
FROM node:20.17.0 AS builder


RUN mkdir -p /home/app

WORKDIR /home/app

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install

# Final image
FROM node:20.17.0-slim

USER node

COPY --from=builder /home/app /home/app

WORKDIR /home/app

EXPOSE 3000

CMD ["npm", "run", "dev"]