components:
  schemas:
    Producto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
        descripcion:
          type: string
        tipo:
          type: string
        img:
          type: string
      xml:
        name: Producto
